### ISSUE TITLE
EXE comes up as virus

### ISSUE THREAD

**Issue by xaerorazor** [Ninjin89/Types-to-Expansion-Market-Converter-UI#1]
Good Day,
FYI: Your program came up under my Virus Quarantine this evening.
![Screenshot 2023-11-03 172827](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/assets/6181154/254d1548-ad20-4a1b-b018-bee48a5ef117)

**Comment by Ninjin89** [comment]
It's a false positive you could scan it at VirusTotal. I can't tell you at the moment why it is like that. On my WIndows 11 it works without getting flagged.

**Comment by Ninjin89** [comment]
So i found out wh it does get flagged, its a false positive for sure.

Its because of the Buttons for adding attachments,adding itm to market and creation of new marketfile.
The Antivirus scans flag it because they think it opens a port and waiting for connection but the tool doesnt have anyfunction like this its kinda weird, even if i created this Converter freshly i get this even on a fresh c# project.
